name: journal-retrieval-code

channels:
  - 

dependencies:
  - python=3.12
  - numpy
  - pandas
  - biopython  
  - lxml
  - huggingface-hub 
  - flake8
  - datasets 
  - pyarrow
  - pip
  - pip:
    - -e .  # install package in development mode